---
# first ensure our target directory exists
- name: Ensure target directory exists
  file:
    dest: "/etc/"
    state: directory

- name: Etc Files
  become: true
  template:
    src: '{{ item.src }}'
    dest: /etc/{{ item.path }}
    mode: '{{ item.mode }}'
    owner: "root" 
  with_filetree: ./
  when: item.state == 'file'

