---
# tasks file for ufw
- name: install ufw
  become: true
  pacman:
    name: ufw
    state: present

- name: enable ufw
  become: true
  ufw:
    state: enabled
    name: syncthing

- name: enable systemd service
  become: true
  systemd:
    state: started
    name: ufw
    enabled: yes
