---
# tasks file for ufw
- name: install ufw
  become: true
  pacman:
    name: ufw
    state: present

- name: enable ufw
  become: true
  ufw:
    state: enabled
    policy: allow

- name: enable rules
  become: true
  ufw:
    name: syncthing
    rule: allow


- name: enable systemd service
  become: true
  systemd:
    state: started
    name: ufw
    enabled: yes
