---
- name: dependencies
  pacman: 
    name: python-jmespath
    state: present
  become: true

# first ensure our target directory exists
- name: Ensure target directory exists
  file:
    dest: "~/.config/"
    state: directory

- name: check for cruft
  stat:
    path: '~/.config/{{ item.path | basename}}' 
  with_filetree: "~/configs/"
  when: item.path | basename == item.path and item.path | basename != ".stfolder"
  register: configs

#- debug: var=item
#  with_items: "{{ configs | json_query('results[*].stat') }}"


- name: remove the old cruft
  file: 
    path: '~/.config/{{ item.path | basename}}'
    state: absent
  with_items: "{{ configs | json_query('results[*].stat') }}"
  when: (item.isdir is defined and item.isdir) or (item.isreg is defined and item.isreg)

- name: setup config symlinks
  file: 
    src: '{{ item.root + (item.path | basename) }}'
    path: '~/.config/{{ item.path | basename}}' 
    state: link 
    force: true
  with_filetree: "~/configs/"
  when: item.path | basename == item.path and item.path | basename != ".stfolder"
