---
# first ensure our target directory exists
- name: Ensure target directory exists
  file:
    dest: "~/.config/"
    state: directory

- name: setup config symlinks
  file: 
    src: '{{ item.root + (item.path | basename) }}'
    path: '/home/jesse/.config/{{ item.path | basename}}' 
    state: link 
    force: true
  with_filetree: "~/configs/"
  when: item.path | basename == item.path and item.path | basename != ".stfolder"
