
# first ensure our target directory exists
- name: Ensure target directory exists
  become: true
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "/etc/rc.d"
    - "/usr/lib/systemd/system-sleep/"

- name: rc.local
  become: true
  template:
    src: 'rc.local'
    dest: /etc/rc.d/rc.local
    mode: 0644
    owner: "root" 

- name: alsa.conf
  become: true
  template:
    src: alsa.conf
    dest: /etc/modprobe.d/alsa.conf
    mode: 0644
    owner: root

- name: chrome os sound suspend
  become: true
  template:
    src: 'cros-sound-suspend.sh'
    dest: /usr/lib/systemd/system-sleep/cros-sound-suspend.sh
    mode: 0755
    owner: "root" 

